# generated by 'clang2py'
# flags '-c -k cdefmstu -o /Users/jeffreyweiss/git/rtma/examples/python/request_reply/message_defs.py /Users/jeffreyweiss/git/rtma/examples/python/request_reply/message_defs.h'
# -*- coding: utf-8 -*-
#
# TARGET arch is: []
# WORD_SIZE is: 8
# POINTER_SIZE is: 8
# LONGDOUBLE_SIZE is: 16
#
import ctypes




MID_REQUEST = 12 # macro
MID_REPLY = 13 # macro
MT_REQUEST_TEST_DATA = 101 # macro
MT_TEST_DATA = 102 # macro
class struct_c__SA_MDF_TEST_DATA(ctypes.Structure):
    _pack_ = True # source:False
    _fields_ = [
    ('a', ctypes.c_int32),
    ('b', ctypes.c_int32),
    ('x', ctypes.c_double),
     ]

MDF_TEST_DATA = struct_c__SA_MDF_TEST_DATA
__all__ = \
    ['MDF_TEST_DATA', 'MID_REPLY', 'MID_REQUEST',
    'MT_REQUEST_TEST_DATA', 'MT_TEST_DATA',
    'struct_c__SA_MDF_TEST_DATA']
