# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.




"""
Python interface to the University of Pittsburgh Motor Control Lab's Real Time Messaging Architecture (RTMA).
"""


from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PyRTMA', [dirname(__file__)])
        except ImportError:
            import _PyRTMA
            return _PyRTMA
        if fp is not None:
            try:
                _mod = imp.load_module('_PyRTMA', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _PyRTMA = swig_import_helper()
    del swig_import_helper
else:
    import _PyRTMA
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def void_ptr(*args):
  """void_ptr(long long n) -> void *"""
  return _PyRTMA.void_ptr(*args)
from ctypes import memmove, addressof, sizeof

def copy_from_msg(data, cmsg):
	memmove(addressof(data), cmsg.data, sizeof(data))

def copy_to_msg(data, cmsg):
	cmsg.SetData(void_ptr(addressof(data)), sizeof(data))

def read_msg_data(data, cmsg):
    cmsg.GetData(void_ptr(addressof(data)))

DEFAULT_PIPE_SERVER_NAME_FOR_MODULES = _PyRTMA.DEFAULT_PIPE_SERVER_NAME_FOR_MODULES
DEFAULT_PIPE_SERVER_NAME_FOR_MM = _PyRTMA.DEFAULT_PIPE_SERVER_NAME_FOR_MM
class CMessage(_object):
    """Proxy of C++ CMessage class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CMessage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CMessage, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _PyRTMA.CMessage_data_set
    __swig_getmethods__["data"] = _PyRTMA.CMessage_data_get
    if _newclass:data = _swig_property(_PyRTMA.CMessage_data_get, _PyRTMA.CMessage_data_set)
    __swig_setmethods__["large_data"] = _PyRTMA.CMessage_large_data_set
    __swig_getmethods__["large_data"] = _PyRTMA.CMessage_large_data_get
    if _newclass:large_data = _swig_property(_PyRTMA.CMessage_large_data_get, _PyRTMA.CMessage_large_data_set)
    def __init__(self, *args): 
        """
        __init__(CMessage self) -> CMessage
        __init__(CMessage self, MSG_TYPE mt) -> CMessage
        __init__(CMessage self, MSG_TYPE mt, void * pData, int num_bytes) -> CMessage
        """
        this = _PyRTMA.new_CMessage(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_CMessage
    __del__ = lambda self : None;
    def GetDataPointer(self):
        """GetDataPointer(CMessage self) -> void *"""
        return _PyRTMA.CMessage_GetDataPointer(self)

    def GetData(self, *args):
        """GetData(CMessage self, void * pData) -> int"""
        return _PyRTMA.CMessage_GetData(self, *args)

    def SetData(self, *args):
        """SetData(CMessage self, void * pData, int num_bytes) -> int"""
        return _PyRTMA.CMessage_SetData(self, *args)

    def AllocateData(self, *args):
        """AllocateData(CMessage self, int num_bytes) -> int"""
        return _PyRTMA.CMessage_AllocateData(self, *args)

    def Set(self, *args):
        """
        Set(CMessage self, MSG_TYPE mt, void * pData=None, int num_bytes=0) -> int
        Set(CMessage self, MSG_TYPE mt, void * pData=None) -> int
        Set(CMessage self, MSG_TYPE mt) -> int
        """
        return _PyRTMA.CMessage_Set(self, *args)

    def Receive(self, *args):
        """
        Receive(CMessage self, UPipe * input_pipe) -> int
        Receive(CMessage self, UPipe * input_pipe, double timeout) -> int
        """
        return _PyRTMA.CMessage_Receive(self, *args)

    def Send(self, *args):
        """
        Send(CMessage self, UPipe * output_pipe) -> int
        Send(CMessage self, UPipe * output_pipe, double timeout) -> int
        """
        return _PyRTMA.CMessage_Send(self, *args)

    def IsDynamic(self):
        """IsDynamic(CMessage self) -> bool"""
        return _PyRTMA.CMessage_IsDynamic(self)

    def GetHeader(self):
        """GetHeader(CMessage self) -> RTMA_MSG_HEADER"""
        return _PyRTMA.CMessage_GetHeader(self)

CMessage_swigregister = _PyRTMA.CMessage_swigregister
CMessage_swigregister(CMessage)

class RTMA_Module(_object):
    """Proxy of C++ RTMA_Module class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RTMA_Module, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RTMA_Module, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(RTMA_Module self) -> RTMA_Module
        __init__(RTMA_Module self, MODULE_ID ModuleID, HOST_ID HostID) -> RTMA_Module
        """
        this = _PyRTMA.new_RTMA_Module(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_RTMA_Module
    __del__ = lambda self : None;
    def Cleanup(self):
        """Cleanup(RTMA_Module self)"""
        return _PyRTMA.RTMA_Module_Cleanup(self)

    def InitVariables(self, *args):
        """InitVariables(RTMA_Module self, MODULE_ID ModuleID, HOST_ID HostID)"""
        return _PyRTMA.RTMA_Module_InitVariables(self, *args)

    def ConnectToMMM(self, *args):
        """
        ConnectToMMM(RTMA_Module self, int logger_status=0, int read_dd_file=0, int daemon_status=0) -> int
        ConnectToMMM(RTMA_Module self, int logger_status=0, int read_dd_file=0) -> int
        ConnectToMMM(RTMA_Module self, int logger_status=0) -> int
        ConnectToMMM(RTMA_Module self) -> int
        ConnectToMMM(RTMA_Module self, char * server_name, int logger_status=0, int read_dd_file=0, int daemon_status=0) -> int
        ConnectToMMM(RTMA_Module self, char * server_name, int logger_status=0, int read_dd_file=0) -> int
        ConnectToMMM(RTMA_Module self, char * server_name, int logger_status=0) -> int
        ConnectToMMM(RTMA_Module self, char * server_name) -> int
        """
        return _PyRTMA.RTMA_Module_ConnectToMMM(self, *args)

    def DisconnectFromMMM(self):
        """DisconnectFromMMM(RTMA_Module self) -> int"""
        return _PyRTMA.RTMA_Module_DisconnectFromMMM(self)

    def IsConnected(self):
        """IsConnected(RTMA_Module self) -> int"""
        return _PyRTMA.RTMA_Module_IsConnected(self)

    def SendModuleReady(self):
        """SendModuleReady(RTMA_Module self) -> int"""
        return _PyRTMA.RTMA_Module_SendModuleReady(self)

    def Subscribe(self, *args):
        """Subscribe(RTMA_Module self, MSG_TYPE MessageType) -> int"""
        return _PyRTMA.RTMA_Module_Subscribe(self, *args)

    def Unsubscribe(self, *args):
        """Unsubscribe(RTMA_Module self, MSG_TYPE MessageType) -> int"""
        return _PyRTMA.RTMA_Module_Unsubscribe(self, *args)

    def PauseSubscription(self, *args):
        """PauseSubscription(RTMA_Module self, MSG_TYPE MessageType) -> int"""
        return _PyRTMA.RTMA_Module_PauseSubscription(self, *args)

    def ResumeSubscription(self, *args):
        """ResumeSubscription(RTMA_Module self, MSG_TYPE MessageType) -> int"""
        return _PyRTMA.RTMA_Module_ResumeSubscription(self, *args)

    def SendMessage(self, *args):
        """
        SendMessage(RTMA_Module self, CMessage M, MODULE_ID dest_mod_id=0, HOST_ID dest_host_id=0) -> int
        SendMessage(RTMA_Module self, CMessage M, MODULE_ID dest_mod_id=0) -> int
        SendMessage(RTMA_Module self, CMessage M) -> int
        """
        return _PyRTMA.RTMA_Module_SendMessage(self, *args)

    def SendMessageRTMA(self, *args):
        """
        SendMessageRTMA(RTMA_Module self, CMessage M, MODULE_ID dest_mod_id=0, HOST_ID dest_host_id=0) -> int
        SendMessageRTMA(RTMA_Module self, CMessage M, MODULE_ID dest_mod_id=0) -> int
        SendMessageRTMA(RTMA_Module self, CMessage M) -> int
        """
        return _PyRTMA.RTMA_Module_SendMessageRTMA(self, *args)

    def SendSignal(self, *args):
        """
        SendSignal(RTMA_Module self, MSG_TYPE MessageType, MODULE_ID dest_mod_id=0, HOST_ID dest_host_id=0) -> int
        SendSignal(RTMA_Module self, MSG_TYPE MessageType, MODULE_ID dest_mod_id=0) -> int
        SendSignal(RTMA_Module self, MSG_TYPE MessageType) -> int
        """
        return _PyRTMA.RTMA_Module_SendSignal(self, *args)

    def SendSelfSignal(self, *args):
        """SendSelfSignal(RTMA_Module self, MSG_TYPE MessageType) -> int"""
        return _PyRTMA.RTMA_Module_SendSelfSignal(self, *args)

    def ReadMessage(self, *args):
        """
        ReadMessage(RTMA_Module self, CMessage M, double timeout=-1) -> int
        ReadMessage(RTMA_Module self, CMessage M) -> int
        """
        return _PyRTMA.RTMA_Module_ReadMessage(self, *args)

    def WaitForSignal(self, *args):
        """
        WaitForSignal(RTMA_Module self, MSG_TYPE SigType, int blocking=1) -> int
        WaitForSignal(RTMA_Module self, MSG_TYPE SigType) -> int
        """
        return _PyRTMA.RTMA_Module_WaitForSignal(self, *args)

    def WaitForMessage(self, *args):
        """
        WaitForMessage(RTMA_Module self, CMessage M, MSG_TYPE MsgType=-1)
        WaitForMessage(RTMA_Module self, CMessage M)
        """
        return _PyRTMA.RTMA_Module_WaitForMessage(self, *args)

    def SetTimer(self, *args):
        """SetTimer(RTMA_Module self, unsigned int time_ms) -> int"""
        return _PyRTMA.RTMA_Module_SetTimer(self, *args)

    def CancelTimer(self, *args):
        """CancelTimer(RTMA_Module self, int timer_id) -> int"""
        return _PyRTMA.RTMA_Module_CancelTimer(self, *args)

    def SelfNotifyExpiredTimer(self, *args):
        """SelfNotifyExpiredTimer(RTMA_Module self, int timer_id) -> int"""
        return _PyRTMA.RTMA_Module_SelfNotifyExpiredTimer(self, *args)

    def UpTime(self):
        """UpTime(RTMA_Module self) -> double"""
        return _PyRTMA.RTMA_Module_UpTime(self)

    def GetPid(self):
        """GetPid(RTMA_Module self) -> int"""
        return _PyRTMA.RTMA_Module_GetPid(self)

    def GetMessageCount(self):
        """GetMessageCount(RTMA_Module self) -> int"""
        return _PyRTMA.RTMA_Module_GetMessageCount(self)

    def GetHostID(self):
        """GetHostID(RTMA_Module self) -> HOST_ID"""
        return _PyRTMA.RTMA_Module_GetHostID(self)

    def GetModuleID(self):
        """GetModuleID(RTMA_Module self) -> MODULE_ID"""
        return _PyRTMA.RTMA_Module_GetModuleID(self)

RTMA_Module_swigregister = _PyRTMA.RTMA_Module_swigregister
RTMA_Module_swigregister(RTMA_Module)


def SetMyPriority(*args):
  """SetMyPriority(int priority_class) -> int"""
  return _PyRTMA.SetMyPriority(*args)

def GetMyPriority():
  """GetMyPriority() -> int"""
  return _PyRTMA.GetMyPriority()
MAX_MODULES = _PyRTMA.MAX_MODULES
DYN_MOD_ID_START = _PyRTMA.DYN_MOD_ID_START
MAX_HOSTS = _PyRTMA.MAX_HOSTS
MAX_MESSAGE_TYPES = _PyRTMA.MAX_MESSAGE_TYPES
MIN_STREAM_TYPE = _PyRTMA.MIN_STREAM_TYPE
MAX_TIMERS = _PyRTMA.MAX_TIMERS
MAX_INTERNAL_TIMERS = _PyRTMA.MAX_INTERNAL_TIMERS
MAX_RTMA_MSG_TYPE = _PyRTMA.MAX_RTMA_MSG_TYPE
MAX_RTMA_MODULE_ID = _PyRTMA.MAX_RTMA_MODULE_ID
class RTMA_MSG_HEADER(_object):
    """Proxy of C++ RTMA_MSG_HEADER class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RTMA_MSG_HEADER, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RTMA_MSG_HEADER, name)
    __repr__ = _swig_repr
    __swig_setmethods__["msg_type"] = _PyRTMA.RTMA_MSG_HEADER_msg_type_set
    __swig_getmethods__["msg_type"] = _PyRTMA.RTMA_MSG_HEADER_msg_type_get
    if _newclass:msg_type = _swig_property(_PyRTMA.RTMA_MSG_HEADER_msg_type_get, _PyRTMA.RTMA_MSG_HEADER_msg_type_set)
    __swig_setmethods__["msg_count"] = _PyRTMA.RTMA_MSG_HEADER_msg_count_set
    __swig_getmethods__["msg_count"] = _PyRTMA.RTMA_MSG_HEADER_msg_count_get
    if _newclass:msg_count = _swig_property(_PyRTMA.RTMA_MSG_HEADER_msg_count_get, _PyRTMA.RTMA_MSG_HEADER_msg_count_set)
    __swig_setmethods__["send_time"] = _PyRTMA.RTMA_MSG_HEADER_send_time_set
    __swig_getmethods__["send_time"] = _PyRTMA.RTMA_MSG_HEADER_send_time_get
    if _newclass:send_time = _swig_property(_PyRTMA.RTMA_MSG_HEADER_send_time_get, _PyRTMA.RTMA_MSG_HEADER_send_time_set)
    __swig_setmethods__["recv_time"] = _PyRTMA.RTMA_MSG_HEADER_recv_time_set
    __swig_getmethods__["recv_time"] = _PyRTMA.RTMA_MSG_HEADER_recv_time_get
    if _newclass:recv_time = _swig_property(_PyRTMA.RTMA_MSG_HEADER_recv_time_get, _PyRTMA.RTMA_MSG_HEADER_recv_time_set)
    __swig_setmethods__["src_host_id"] = _PyRTMA.RTMA_MSG_HEADER_src_host_id_set
    __swig_getmethods__["src_host_id"] = _PyRTMA.RTMA_MSG_HEADER_src_host_id_get
    if _newclass:src_host_id = _swig_property(_PyRTMA.RTMA_MSG_HEADER_src_host_id_get, _PyRTMA.RTMA_MSG_HEADER_src_host_id_set)
    __swig_setmethods__["src_mod_id"] = _PyRTMA.RTMA_MSG_HEADER_src_mod_id_set
    __swig_getmethods__["src_mod_id"] = _PyRTMA.RTMA_MSG_HEADER_src_mod_id_get
    if _newclass:src_mod_id = _swig_property(_PyRTMA.RTMA_MSG_HEADER_src_mod_id_get, _PyRTMA.RTMA_MSG_HEADER_src_mod_id_set)
    __swig_setmethods__["dest_host_id"] = _PyRTMA.RTMA_MSG_HEADER_dest_host_id_set
    __swig_getmethods__["dest_host_id"] = _PyRTMA.RTMA_MSG_HEADER_dest_host_id_get
    if _newclass:dest_host_id = _swig_property(_PyRTMA.RTMA_MSG_HEADER_dest_host_id_get, _PyRTMA.RTMA_MSG_HEADER_dest_host_id_set)
    __swig_setmethods__["dest_mod_id"] = _PyRTMA.RTMA_MSG_HEADER_dest_mod_id_set
    __swig_getmethods__["dest_mod_id"] = _PyRTMA.RTMA_MSG_HEADER_dest_mod_id_get
    if _newclass:dest_mod_id = _swig_property(_PyRTMA.RTMA_MSG_HEADER_dest_mod_id_get, _PyRTMA.RTMA_MSG_HEADER_dest_mod_id_set)
    __swig_setmethods__["num_data_bytes"] = _PyRTMA.RTMA_MSG_HEADER_num_data_bytes_set
    __swig_getmethods__["num_data_bytes"] = _PyRTMA.RTMA_MSG_HEADER_num_data_bytes_get
    if _newclass:num_data_bytes = _swig_property(_PyRTMA.RTMA_MSG_HEADER_num_data_bytes_get, _PyRTMA.RTMA_MSG_HEADER_num_data_bytes_set)
    __swig_setmethods__["remaining_bytes"] = _PyRTMA.RTMA_MSG_HEADER_remaining_bytes_set
    __swig_getmethods__["remaining_bytes"] = _PyRTMA.RTMA_MSG_HEADER_remaining_bytes_get
    if _newclass:remaining_bytes = _swig_property(_PyRTMA.RTMA_MSG_HEADER_remaining_bytes_get, _PyRTMA.RTMA_MSG_HEADER_remaining_bytes_set)
    __swig_setmethods__["is_dynamic"] = _PyRTMA.RTMA_MSG_HEADER_is_dynamic_set
    __swig_getmethods__["is_dynamic"] = _PyRTMA.RTMA_MSG_HEADER_is_dynamic_get
    if _newclass:is_dynamic = _swig_property(_PyRTMA.RTMA_MSG_HEADER_is_dynamic_get, _PyRTMA.RTMA_MSG_HEADER_is_dynamic_set)
    __swig_setmethods__["reserved"] = _PyRTMA.RTMA_MSG_HEADER_reserved_set
    __swig_getmethods__["reserved"] = _PyRTMA.RTMA_MSG_HEADER_reserved_get
    if _newclass:reserved = _swig_property(_PyRTMA.RTMA_MSG_HEADER_reserved_get, _PyRTMA.RTMA_MSG_HEADER_reserved_set)
    def __init__(self): 
        """__init__(RTMA_MSG_HEADER self) -> RTMA_MSG_HEADER"""
        this = _PyRTMA.new_RTMA_MSG_HEADER()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_RTMA_MSG_HEADER
    __del__ = lambda self : None;
RTMA_MSG_HEADER_swigregister = _PyRTMA.RTMA_MSG_HEADER_swigregister
RTMA_MSG_HEADER_swigregister(RTMA_MSG_HEADER)

MAX_CONTIGUOUS_MESSAGE_DATA = _PyRTMA.MAX_CONTIGUOUS_MESSAGE_DATA
class RTMA_MESSAGE(_object):
    """Proxy of C++ RTMA_MESSAGE class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RTMA_MESSAGE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RTMA_MESSAGE, name)
    __repr__ = _swig_repr
    __swig_setmethods__["msg_type"] = _PyRTMA.RTMA_MESSAGE_msg_type_set
    __swig_getmethods__["msg_type"] = _PyRTMA.RTMA_MESSAGE_msg_type_get
    if _newclass:msg_type = _swig_property(_PyRTMA.RTMA_MESSAGE_msg_type_get, _PyRTMA.RTMA_MESSAGE_msg_type_set)
    __swig_setmethods__["msg_count"] = _PyRTMA.RTMA_MESSAGE_msg_count_set
    __swig_getmethods__["msg_count"] = _PyRTMA.RTMA_MESSAGE_msg_count_get
    if _newclass:msg_count = _swig_property(_PyRTMA.RTMA_MESSAGE_msg_count_get, _PyRTMA.RTMA_MESSAGE_msg_count_set)
    __swig_setmethods__["send_time"] = _PyRTMA.RTMA_MESSAGE_send_time_set
    __swig_getmethods__["send_time"] = _PyRTMA.RTMA_MESSAGE_send_time_get
    if _newclass:send_time = _swig_property(_PyRTMA.RTMA_MESSAGE_send_time_get, _PyRTMA.RTMA_MESSAGE_send_time_set)
    __swig_setmethods__["recv_time"] = _PyRTMA.RTMA_MESSAGE_recv_time_set
    __swig_getmethods__["recv_time"] = _PyRTMA.RTMA_MESSAGE_recv_time_get
    if _newclass:recv_time = _swig_property(_PyRTMA.RTMA_MESSAGE_recv_time_get, _PyRTMA.RTMA_MESSAGE_recv_time_set)
    __swig_setmethods__["src_host_id"] = _PyRTMA.RTMA_MESSAGE_src_host_id_set
    __swig_getmethods__["src_host_id"] = _PyRTMA.RTMA_MESSAGE_src_host_id_get
    if _newclass:src_host_id = _swig_property(_PyRTMA.RTMA_MESSAGE_src_host_id_get, _PyRTMA.RTMA_MESSAGE_src_host_id_set)
    __swig_setmethods__["src_mod_id"] = _PyRTMA.RTMA_MESSAGE_src_mod_id_set
    __swig_getmethods__["src_mod_id"] = _PyRTMA.RTMA_MESSAGE_src_mod_id_get
    if _newclass:src_mod_id = _swig_property(_PyRTMA.RTMA_MESSAGE_src_mod_id_get, _PyRTMA.RTMA_MESSAGE_src_mod_id_set)
    __swig_setmethods__["dest_host_id"] = _PyRTMA.RTMA_MESSAGE_dest_host_id_set
    __swig_getmethods__["dest_host_id"] = _PyRTMA.RTMA_MESSAGE_dest_host_id_get
    if _newclass:dest_host_id = _swig_property(_PyRTMA.RTMA_MESSAGE_dest_host_id_get, _PyRTMA.RTMA_MESSAGE_dest_host_id_set)
    __swig_setmethods__["dest_mod_id"] = _PyRTMA.RTMA_MESSAGE_dest_mod_id_set
    __swig_getmethods__["dest_mod_id"] = _PyRTMA.RTMA_MESSAGE_dest_mod_id_get
    if _newclass:dest_mod_id = _swig_property(_PyRTMA.RTMA_MESSAGE_dest_mod_id_get, _PyRTMA.RTMA_MESSAGE_dest_mod_id_set)
    __swig_setmethods__["num_data_bytes"] = _PyRTMA.RTMA_MESSAGE_num_data_bytes_set
    __swig_getmethods__["num_data_bytes"] = _PyRTMA.RTMA_MESSAGE_num_data_bytes_get
    if _newclass:num_data_bytes = _swig_property(_PyRTMA.RTMA_MESSAGE_num_data_bytes_get, _PyRTMA.RTMA_MESSAGE_num_data_bytes_set)
    __swig_setmethods__["remaining_bytes"] = _PyRTMA.RTMA_MESSAGE_remaining_bytes_set
    __swig_getmethods__["remaining_bytes"] = _PyRTMA.RTMA_MESSAGE_remaining_bytes_get
    if _newclass:remaining_bytes = _swig_property(_PyRTMA.RTMA_MESSAGE_remaining_bytes_get, _PyRTMA.RTMA_MESSAGE_remaining_bytes_set)
    __swig_setmethods__["is_dynamic"] = _PyRTMA.RTMA_MESSAGE_is_dynamic_set
    __swig_getmethods__["is_dynamic"] = _PyRTMA.RTMA_MESSAGE_is_dynamic_get
    if _newclass:is_dynamic = _swig_property(_PyRTMA.RTMA_MESSAGE_is_dynamic_get, _PyRTMA.RTMA_MESSAGE_is_dynamic_set)
    __swig_setmethods__["reserved"] = _PyRTMA.RTMA_MESSAGE_reserved_set
    __swig_getmethods__["reserved"] = _PyRTMA.RTMA_MESSAGE_reserved_get
    if _newclass:reserved = _swig_property(_PyRTMA.RTMA_MESSAGE_reserved_get, _PyRTMA.RTMA_MESSAGE_reserved_set)
    __swig_setmethods__["data"] = _PyRTMA.RTMA_MESSAGE_data_set
    __swig_getmethods__["data"] = _PyRTMA.RTMA_MESSAGE_data_get
    if _newclass:data = _swig_property(_PyRTMA.RTMA_MESSAGE_data_get, _PyRTMA.RTMA_MESSAGE_data_set)
    def __init__(self): 
        """__init__(RTMA_MESSAGE self) -> RTMA_MESSAGE"""
        this = _PyRTMA.new_RTMA_MESSAGE()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_RTMA_MESSAGE
    __del__ = lambda self : None;
RTMA_MESSAGE_swigregister = _PyRTMA.RTMA_MESSAGE_swigregister
RTMA_MESSAGE_swigregister(RTMA_MESSAGE)

MID_MESSAGE_MANAGER = _PyRTMA.MID_MESSAGE_MANAGER
MID_COMMAND_MODULE = _PyRTMA.MID_COMMAND_MODULE
MID_APPLICATION_MODULE = _PyRTMA.MID_APPLICATION_MODULE
MID_NETWORK_RELAY = _PyRTMA.MID_NETWORK_RELAY
MID_STATUS_MODULE = _PyRTMA.MID_STATUS_MODULE
MID_QUICKLOGGER = _PyRTMA.MID_QUICKLOGGER
HID_LOCAL_HOST = _PyRTMA.HID_LOCAL_HOST
HID_ALL_HOSTS = _PyRTMA.HID_ALL_HOSTS
ALL_MESSAGE_TYPES = _PyRTMA.ALL_MESSAGE_TYPES
MT_EXIT = _PyRTMA.MT_EXIT
MT_KILL = _PyRTMA.MT_KILL
MT_ACKNOWLEDGE = _PyRTMA.MT_ACKNOWLEDGE
MT_FAIL_SUBSCRIBE = _PyRTMA.MT_FAIL_SUBSCRIBE
class MDF_FAIL_SUBSCRIBE(_object):
    """Proxy of C++ MDF_FAIL_SUBSCRIBE class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_FAIL_SUBSCRIBE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_FAIL_SUBSCRIBE, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mod_id"] = _PyRTMA.MDF_FAIL_SUBSCRIBE_mod_id_set
    __swig_getmethods__["mod_id"] = _PyRTMA.MDF_FAIL_SUBSCRIBE_mod_id_get
    if _newclass:mod_id = _swig_property(_PyRTMA.MDF_FAIL_SUBSCRIBE_mod_id_get, _PyRTMA.MDF_FAIL_SUBSCRIBE_mod_id_set)
    __swig_setmethods__["reserved"] = _PyRTMA.MDF_FAIL_SUBSCRIBE_reserved_set
    __swig_getmethods__["reserved"] = _PyRTMA.MDF_FAIL_SUBSCRIBE_reserved_get
    if _newclass:reserved = _swig_property(_PyRTMA.MDF_FAIL_SUBSCRIBE_reserved_get, _PyRTMA.MDF_FAIL_SUBSCRIBE_reserved_set)
    __swig_setmethods__["msg_type"] = _PyRTMA.MDF_FAIL_SUBSCRIBE_msg_type_set
    __swig_getmethods__["msg_type"] = _PyRTMA.MDF_FAIL_SUBSCRIBE_msg_type_get
    if _newclass:msg_type = _swig_property(_PyRTMA.MDF_FAIL_SUBSCRIBE_msg_type_get, _PyRTMA.MDF_FAIL_SUBSCRIBE_msg_type_set)
    def __init__(self): 
        """__init__(MDF_FAIL_SUBSCRIBE self) -> MDF_FAIL_SUBSCRIBE"""
        this = _PyRTMA.new_MDF_FAIL_SUBSCRIBE()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_FAIL_SUBSCRIBE
    __del__ = lambda self : None;
MDF_FAIL_SUBSCRIBE_swigregister = _PyRTMA.MDF_FAIL_SUBSCRIBE_swigregister
MDF_FAIL_SUBSCRIBE_swigregister(MDF_FAIL_SUBSCRIBE)

MT_FAILED_MESSAGE = _PyRTMA.MT_FAILED_MESSAGE
class MDF_FAILED_MESSAGE(_object):
    """Proxy of C++ MDF_FAILED_MESSAGE class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_FAILED_MESSAGE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_FAILED_MESSAGE, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dest_mod_id"] = _PyRTMA.MDF_FAILED_MESSAGE_dest_mod_id_set
    __swig_getmethods__["dest_mod_id"] = _PyRTMA.MDF_FAILED_MESSAGE_dest_mod_id_get
    if _newclass:dest_mod_id = _swig_property(_PyRTMA.MDF_FAILED_MESSAGE_dest_mod_id_get, _PyRTMA.MDF_FAILED_MESSAGE_dest_mod_id_set)
    __swig_setmethods__["reserved"] = _PyRTMA.MDF_FAILED_MESSAGE_reserved_set
    __swig_getmethods__["reserved"] = _PyRTMA.MDF_FAILED_MESSAGE_reserved_get
    if _newclass:reserved = _swig_property(_PyRTMA.MDF_FAILED_MESSAGE_reserved_get, _PyRTMA.MDF_FAILED_MESSAGE_reserved_set)
    __swig_setmethods__["time_of_failure"] = _PyRTMA.MDF_FAILED_MESSAGE_time_of_failure_set
    __swig_getmethods__["time_of_failure"] = _PyRTMA.MDF_FAILED_MESSAGE_time_of_failure_get
    if _newclass:time_of_failure = _swig_property(_PyRTMA.MDF_FAILED_MESSAGE_time_of_failure_get, _PyRTMA.MDF_FAILED_MESSAGE_time_of_failure_set)
    __swig_setmethods__["msg_header"] = _PyRTMA.MDF_FAILED_MESSAGE_msg_header_set
    __swig_getmethods__["msg_header"] = _PyRTMA.MDF_FAILED_MESSAGE_msg_header_get
    if _newclass:msg_header = _swig_property(_PyRTMA.MDF_FAILED_MESSAGE_msg_header_get, _PyRTMA.MDF_FAILED_MESSAGE_msg_header_set)
    def __init__(self): 
        """__init__(MDF_FAILED_MESSAGE self) -> MDF_FAILED_MESSAGE"""
        this = _PyRTMA.new_MDF_FAILED_MESSAGE()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_FAILED_MESSAGE
    __del__ = lambda self : None;
MDF_FAILED_MESSAGE_swigregister = _PyRTMA.MDF_FAILED_MESSAGE_swigregister
MDF_FAILED_MESSAGE_swigregister(MDF_FAILED_MESSAGE)

MT_MM_ERROR = _PyRTMA.MT_MM_ERROR
MT_MM_INFO = _PyRTMA.MT_MM_INFO
MT_CONNECT = _PyRTMA.MT_CONNECT
class MDF_CONNECT(_object):
    """Proxy of C++ MDF_CONNECT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_CONNECT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_CONNECT, name)
    __repr__ = _swig_repr
    __swig_setmethods__["logger_status"] = _PyRTMA.MDF_CONNECT_logger_status_set
    __swig_getmethods__["logger_status"] = _PyRTMA.MDF_CONNECT_logger_status_get
    if _newclass:logger_status = _swig_property(_PyRTMA.MDF_CONNECT_logger_status_get, _PyRTMA.MDF_CONNECT_logger_status_set)
    __swig_setmethods__["daemon_status"] = _PyRTMA.MDF_CONNECT_daemon_status_set
    __swig_getmethods__["daemon_status"] = _PyRTMA.MDF_CONNECT_daemon_status_get
    if _newclass:daemon_status = _swig_property(_PyRTMA.MDF_CONNECT_daemon_status_get, _PyRTMA.MDF_CONNECT_daemon_status_set)
    def __init__(self): 
        """__init__(MDF_CONNECT self) -> MDF_CONNECT"""
        this = _PyRTMA.new_MDF_CONNECT()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_CONNECT
    __del__ = lambda self : None;
MDF_CONNECT_swigregister = _PyRTMA.MDF_CONNECT_swigregister
MDF_CONNECT_swigregister(MDF_CONNECT)

MT_DISCONNECT = _PyRTMA.MT_DISCONNECT
MT_SUBSCRIBE = _PyRTMA.MT_SUBSCRIBE
MT_UNSUBSCRIBE = _PyRTMA.MT_UNSUBSCRIBE
MT_PAUSE_SUBSCRIPTION = _PyRTMA.MT_PAUSE_SUBSCRIPTION
MT_RESUME_SUBSCRIPTION = _PyRTMA.MT_RESUME_SUBSCRIPTION
MT_SHUTDOWN_RTMA = _PyRTMA.MT_SHUTDOWN_RTMA
MT_SHUTDOWN_APP = _PyRTMA.MT_SHUTDOWN_APP
MT_FORCE_DISCONNECT = _PyRTMA.MT_FORCE_DISCONNECT
class MDF_FORCE_DISCONNECT(_object):
    """Proxy of C++ MDF_FORCE_DISCONNECT class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_FORCE_DISCONNECT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_FORCE_DISCONNECT, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mod_id"] = _PyRTMA.MDF_FORCE_DISCONNECT_mod_id_set
    __swig_getmethods__["mod_id"] = _PyRTMA.MDF_FORCE_DISCONNECT_mod_id_get
    if _newclass:mod_id = _swig_property(_PyRTMA.MDF_FORCE_DISCONNECT_mod_id_get, _PyRTMA.MDF_FORCE_DISCONNECT_mod_id_set)
    def __init__(self): 
        """__init__(MDF_FORCE_DISCONNECT self) -> MDF_FORCE_DISCONNECT"""
        this = _PyRTMA.new_MDF_FORCE_DISCONNECT()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_FORCE_DISCONNECT
    __del__ = lambda self : None;
MDF_FORCE_DISCONNECT_swigregister = _PyRTMA.MDF_FORCE_DISCONNECT_swigregister
MDF_FORCE_DISCONNECT_swigregister(MDF_FORCE_DISCONNECT)

MT_CORE_MODULE_REINIT_ACK = _PyRTMA.MT_CORE_MODULE_REINIT_ACK
MT_MODULE_READY = _PyRTMA.MT_MODULE_READY
class MDF_MODULE_READY(_object):
    """Proxy of C++ MDF_MODULE_READY class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_MODULE_READY, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_MODULE_READY, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pid"] = _PyRTMA.MDF_MODULE_READY_pid_set
    __swig_getmethods__["pid"] = _PyRTMA.MDF_MODULE_READY_pid_get
    if _newclass:pid = _swig_property(_PyRTMA.MDF_MODULE_READY_pid_get, _PyRTMA.MDF_MODULE_READY_pid_set)
    def __init__(self): 
        """__init__(MDF_MODULE_READY self) -> MDF_MODULE_READY"""
        this = _PyRTMA.new_MDF_MODULE_READY()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_MODULE_READY
    __del__ = lambda self : None;
MDF_MODULE_READY_swigregister = _PyRTMA.MDF_MODULE_READY_swigregister
MDF_MODULE_READY_swigregister(MDF_MODULE_READY)

MT_DYNAMIC_DD_READ_ERR = _PyRTMA.MT_DYNAMIC_DD_READ_ERR
MT_DEBUG_TEXT = _PyRTMA.MT_DEBUG_TEXT
MT_AM_EXIT = _PyRTMA.MT_AM_EXIT
MT_START_APP = _PyRTMA.MT_START_APP
MT_STOP_APP = _PyRTMA.MT_STOP_APP
MT_RESTART_APP = _PyRTMA.MT_RESTART_APP
MT_KILL_APP = _PyRTMA.MT_KILL_APP
MT_AM_RE_READ_CONFIG_FILE = _PyRTMA.MT_AM_RE_READ_CONFIG_FILE
MT_AM_GET_APP_NAME = _PyRTMA.MT_AM_GET_APP_NAME
MT_SLAVE_START_APP = _PyRTMA.MT_SLAVE_START_APP
MT_SLAVE_START_APP_ACK = _PyRTMA.MT_SLAVE_START_APP_ACK
class MDF_SLAVE_START_APP_ACK(_object):
    """Proxy of C++ MDF_SLAVE_START_APP_ACK class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_SLAVE_START_APP_ACK, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_SLAVE_START_APP_ACK, name)
    __repr__ = _swig_repr
    __swig_setmethods__["num_remote_hosts"] = _PyRTMA.MDF_SLAVE_START_APP_ACK_num_remote_hosts_set
    __swig_getmethods__["num_remote_hosts"] = _PyRTMA.MDF_SLAVE_START_APP_ACK_num_remote_hosts_get
    if _newclass:num_remote_hosts = _swig_property(_PyRTMA.MDF_SLAVE_START_APP_ACK_num_remote_hosts_get, _PyRTMA.MDF_SLAVE_START_APP_ACK_num_remote_hosts_set)
    def __init__(self): 
        """__init__(MDF_SLAVE_START_APP_ACK self) -> MDF_SLAVE_START_APP_ACK"""
        this = _PyRTMA.new_MDF_SLAVE_START_APP_ACK()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_SLAVE_START_APP_ACK
    __del__ = lambda self : None;
MDF_SLAVE_START_APP_ACK_swigregister = _PyRTMA.MDF_SLAVE_START_APP_ACK_swigregister
MDF_SLAVE_START_APP_ACK_swigregister(MDF_SLAVE_START_APP_ACK)

MT_SLAVE_STOP_APP = _PyRTMA.MT_SLAVE_STOP_APP
MT_SLAVE_KILL_APP = _PyRTMA.MT_SLAVE_KILL_APP
MT_SLAVE_RESTART_APP = _PyRTMA.MT_SLAVE_RESTART_APP
MT_AM_ERROR = _PyRTMA.MT_AM_ERROR
MT_AM_ACKNOWLEDGE = _PyRTMA.MT_AM_ACKNOWLEDGE
MT_FAIL_START_APP = _PyRTMA.MT_FAIL_START_APP
MT_FAIL_STOP_APP = _PyRTMA.MT_FAIL_STOP_APP
MT_FAIL_KILL_APP = _PyRTMA.MT_FAIL_KILL_APP
MT_APP_START_COMPLETE = _PyRTMA.MT_APP_START_COMPLETE
MT_APP_SHUTODWN_COMPLETE = _PyRTMA.MT_APP_SHUTODWN_COMPLETE
MT_APP_RESTART_COMPLETE = _PyRTMA.MT_APP_RESTART_COMPLETE
MT_APP_KILL_COMPLETE = _PyRTMA.MT_APP_KILL_COMPLETE
MT_ALL_MODULES_READY = _PyRTMA.MT_ALL_MODULES_READY
MT_CORE_MODULE_REINIT = _PyRTMA.MT_CORE_MODULE_REINIT
MT_AM_CONFIG_FILE_DATA = _PyRTMA.MT_AM_CONFIG_FILE_DATA
MT_AM_APP_NAME = _PyRTMA.MT_AM_APP_NAME
MT_SLAVE_ALL_MODULES_READY = _PyRTMA.MT_SLAVE_ALL_MODULES_READY
MT_SLAVE_FAIL_START_APP = _PyRTMA.MT_SLAVE_FAIL_START_APP
MT_SLAVE_FAIL_STOP_APP = _PyRTMA.MT_SLAVE_FAIL_STOP_APP
MT_SLAVE_FAIL_KILL_APP = _PyRTMA.MT_SLAVE_FAIL_KILL_APP
MT_SLAVE_APP_SHUTODWN_COMPLETE = _PyRTMA.MT_SLAVE_APP_SHUTODWN_COMPLETE
MT_SLAVE_APP_RESTART_COMPLETE = _PyRTMA.MT_SLAVE_APP_RESTART_COMPLETE
MT_SLAVE_APP_KILL_COMPLETE = _PyRTMA.MT_SLAVE_APP_KILL_COMPLETE
MT_SLAVE_AM_ERROR = _PyRTMA.MT_SLAVE_AM_ERROR
MT_APP_ERROR = _PyRTMA.MT_APP_ERROR
MT_SM_EXIT = _PyRTMA.MT_SM_EXIT
MT_CLOCK_SYNC = _PyRTMA.MT_CLOCK_SYNC
MT_TIMER_EXPIRED = _PyRTMA.MT_TIMER_EXPIRED
class MDF_TIMER_EXPIRED(_object):
    """Proxy of C++ MDF_TIMER_EXPIRED class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_TIMER_EXPIRED, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_TIMER_EXPIRED, name)
    __repr__ = _swig_repr
    __swig_setmethods__["timer_id"] = _PyRTMA.MDF_TIMER_EXPIRED_timer_id_set
    __swig_getmethods__["timer_id"] = _PyRTMA.MDF_TIMER_EXPIRED_timer_id_get
    if _newclass:timer_id = _swig_property(_PyRTMA.MDF_TIMER_EXPIRED_timer_id_get, _PyRTMA.MDF_TIMER_EXPIRED_timer_id_set)
    def __init__(self): 
        """__init__(MDF_TIMER_EXPIRED self) -> MDF_TIMER_EXPIRED"""
        this = _PyRTMA.new_MDF_TIMER_EXPIRED()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_TIMER_EXPIRED
    __del__ = lambda self : None;
MDF_TIMER_EXPIRED_swigregister = _PyRTMA.MDF_TIMER_EXPIRED_swigregister
MDF_TIMER_EXPIRED_swigregister(MDF_TIMER_EXPIRED)

MT_TIMED_OUT = _PyRTMA.MT_TIMED_OUT
MT_SET_TIMER_FAILED = _PyRTMA.MT_SET_TIMER_FAILED
class MDF_SET_TIMER_FAILED(_object):
    """Proxy of C++ MDF_SET_TIMER_FAILED class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_SET_TIMER_FAILED, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_SET_TIMER_FAILED, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mod_id"] = _PyRTMA.MDF_SET_TIMER_FAILED_mod_id_set
    __swig_getmethods__["mod_id"] = _PyRTMA.MDF_SET_TIMER_FAILED_mod_id_get
    if _newclass:mod_id = _swig_property(_PyRTMA.MDF_SET_TIMER_FAILED_mod_id_get, _PyRTMA.MDF_SET_TIMER_FAILED_mod_id_set)
    __swig_setmethods__["timer_id"] = _PyRTMA.MDF_SET_TIMER_FAILED_timer_id_set
    __swig_getmethods__["timer_id"] = _PyRTMA.MDF_SET_TIMER_FAILED_timer_id_get
    if _newclass:timer_id = _swig_property(_PyRTMA.MDF_SET_TIMER_FAILED_timer_id_get, _PyRTMA.MDF_SET_TIMER_FAILED_timer_id_set)
    __swig_setmethods__["snooze_time"] = _PyRTMA.MDF_SET_TIMER_FAILED_snooze_time_set
    __swig_getmethods__["snooze_time"] = _PyRTMA.MDF_SET_TIMER_FAILED_snooze_time_get
    if _newclass:snooze_time = _swig_property(_PyRTMA.MDF_SET_TIMER_FAILED_snooze_time_get, _PyRTMA.MDF_SET_TIMER_FAILED_snooze_time_set)
    def __init__(self): 
        """__init__(MDF_SET_TIMER_FAILED self) -> MDF_SET_TIMER_FAILED"""
        this = _PyRTMA.new_MDF_SET_TIMER_FAILED()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_SET_TIMER_FAILED
    __del__ = lambda self : None;
MDF_SET_TIMER_FAILED_swigregister = _PyRTMA.MDF_SET_TIMER_FAILED_swigregister
MDF_SET_TIMER_FAILED_swigregister(MDF_SET_TIMER_FAILED)

MT_TM_EXIT = _PyRTMA.MT_TM_EXIT
MT_SET_TIMER = _PyRTMA.MT_SET_TIMER
class MDF_SET_TIMER(_object):
    """Proxy of C++ MDF_SET_TIMER class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_SET_TIMER, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_SET_TIMER, name)
    __repr__ = _swig_repr
    __swig_setmethods__["timer_id"] = _PyRTMA.MDF_SET_TIMER_timer_id_set
    __swig_getmethods__["timer_id"] = _PyRTMA.MDF_SET_TIMER_timer_id_get
    if _newclass:timer_id = _swig_property(_PyRTMA.MDF_SET_TIMER_timer_id_get, _PyRTMA.MDF_SET_TIMER_timer_id_set)
    __swig_setmethods__["snooze_time"] = _PyRTMA.MDF_SET_TIMER_snooze_time_set
    __swig_getmethods__["snooze_time"] = _PyRTMA.MDF_SET_TIMER_snooze_time_get
    if _newclass:snooze_time = _swig_property(_PyRTMA.MDF_SET_TIMER_snooze_time_get, _PyRTMA.MDF_SET_TIMER_snooze_time_set)
    def __init__(self): 
        """__init__(MDF_SET_TIMER self) -> MDF_SET_TIMER"""
        this = _PyRTMA.new_MDF_SET_TIMER()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_SET_TIMER
    __del__ = lambda self : None;
MDF_SET_TIMER_swigregister = _PyRTMA.MDF_SET_TIMER_swigregister
MDF_SET_TIMER_swigregister(MDF_SET_TIMER)

MT_CANCEL_TIMER = _PyRTMA.MT_CANCEL_TIMER
class MDF_CANCEL_TIMER(_object):
    """Proxy of C++ MDF_CANCEL_TIMER class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_CANCEL_TIMER, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_CANCEL_TIMER, name)
    __repr__ = _swig_repr
    __swig_setmethods__["timer_id"] = _PyRTMA.MDF_CANCEL_TIMER_timer_id_set
    __swig_getmethods__["timer_id"] = _PyRTMA.MDF_CANCEL_TIMER_timer_id_get
    if _newclass:timer_id = _swig_property(_PyRTMA.MDF_CANCEL_TIMER_timer_id_get, _PyRTMA.MDF_CANCEL_TIMER_timer_id_set)
    def __init__(self): 
        """__init__(MDF_CANCEL_TIMER self) -> MDF_CANCEL_TIMER"""
        this = _PyRTMA.new_MDF_CANCEL_TIMER()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_CANCEL_TIMER
    __del__ = lambda self : None;
MDF_CANCEL_TIMER_swigregister = _PyRTMA.MDF_CANCEL_TIMER_swigregister
MDF_CANCEL_TIMER_swigregister(MDF_CANCEL_TIMER)

MT_LM_EXIT = _PyRTMA.MT_LM_EXIT
MT_MM_READY = _PyRTMA.MT_MM_READY
MT_LM_READY = _PyRTMA.MT_LM_READY
MT_SAVE_MESSAGE_LOG = _PyRTMA.MT_SAVE_MESSAGE_LOG
MAX_LOGGER_FILENAME_LENGTH = _PyRTMA.MAX_LOGGER_FILENAME_LENGTH
class MDF_SAVE_MESSAGE_LOG(_object):
    """Proxy of C++ MDF_SAVE_MESSAGE_LOG class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_SAVE_MESSAGE_LOG, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_SAVE_MESSAGE_LOG, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pathname"] = _PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_set
    __swig_getmethods__["pathname"] = _PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_get
    if _newclass:pathname = _swig_property(_PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_get, _PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_set)
    __swig_setmethods__["pathname_length"] = _PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_length_set
    __swig_getmethods__["pathname_length"] = _PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_length_get
    if _newclass:pathname_length = _swig_property(_PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_length_get, _PyRTMA.MDF_SAVE_MESSAGE_LOG_pathname_length_set)
    def __init__(self): 
        """__init__(MDF_SAVE_MESSAGE_LOG self) -> MDF_SAVE_MESSAGE_LOG"""
        this = _PyRTMA.new_MDF_SAVE_MESSAGE_LOG()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_SAVE_MESSAGE_LOG
    __del__ = lambda self : None;
MDF_SAVE_MESSAGE_LOG_swigregister = _PyRTMA.MDF_SAVE_MESSAGE_LOG_swigregister
MDF_SAVE_MESSAGE_LOG_swigregister(MDF_SAVE_MESSAGE_LOG)

MT_MESSAGE_LOG_SAVED = _PyRTMA.MT_MESSAGE_LOG_SAVED
MT_PAUSE_MESSAGE_LOGGING = _PyRTMA.MT_PAUSE_MESSAGE_LOGGING
MT_RESUME_MESSAGE_LOGGING = _PyRTMA.MT_RESUME_MESSAGE_LOGGING
MT_RESET_MESSAGE_LOG = _PyRTMA.MT_RESET_MESSAGE_LOG
MT_DUMP_MESSAGE_LOG = _PyRTMA.MT_DUMP_MESSAGE_LOG
MT_TIMING_MESSAGE = _PyRTMA.MT_TIMING_MESSAGE
class MDF_TIMING_MESSAGE(_object):
    """Proxy of C++ MDF_TIMING_MESSAGE class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MDF_TIMING_MESSAGE, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MDF_TIMING_MESSAGE, name)
    __repr__ = _swig_repr
    __swig_setmethods__["timing"] = _PyRTMA.MDF_TIMING_MESSAGE_timing_set
    __swig_getmethods__["timing"] = _PyRTMA.MDF_TIMING_MESSAGE_timing_get
    if _newclass:timing = _swig_property(_PyRTMA.MDF_TIMING_MESSAGE_timing_get, _PyRTMA.MDF_TIMING_MESSAGE_timing_set)
    __swig_setmethods__["ModulePID"] = _PyRTMA.MDF_TIMING_MESSAGE_ModulePID_set
    __swig_getmethods__["ModulePID"] = _PyRTMA.MDF_TIMING_MESSAGE_ModulePID_get
    if _newclass:ModulePID = _swig_property(_PyRTMA.MDF_TIMING_MESSAGE_ModulePID_get, _PyRTMA.MDF_TIMING_MESSAGE_ModulePID_set)
    __swig_setmethods__["send_time"] = _PyRTMA.MDF_TIMING_MESSAGE_send_time_set
    __swig_getmethods__["send_time"] = _PyRTMA.MDF_TIMING_MESSAGE_send_time_get
    if _newclass:send_time = _swig_property(_PyRTMA.MDF_TIMING_MESSAGE_send_time_get, _PyRTMA.MDF_TIMING_MESSAGE_send_time_set)
    def __init__(self): 
        """__init__(MDF_TIMING_MESSAGE self) -> MDF_TIMING_MESSAGE"""
        this = _PyRTMA.new_MDF_TIMING_MESSAGE()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PyRTMA.delete_MDF_TIMING_MESSAGE
    __del__ = lambda self : None;
MDF_TIMING_MESSAGE_swigregister = _PyRTMA.MDF_TIMING_MESSAGE_swigregister
MDF_TIMING_MESSAGE_swigregister(MDF_TIMING_MESSAGE)

# This file is compatible with both classic and new-style classes.


